services:
  - type: web
    name: linkedin-clone-backend
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: server
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
